# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy CI

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    # strategy:
    #  matrix:
    #    node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      
      # build Sapper app
      - name: Sapper Build
        uses: truewebartisans/actions-sapper@mater
        with:
          build_mode: "build"
      
      # deploy to server
      - name: Deploy to VPS server via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: __sapper__/build/
          target: ${{ secrets.REMOTE_DIR }}
